# Generated by Django 4.2.1 on 2023-07-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_disco', models.CharField(max_length=40)),
                ('ventas', models.IntegerField()),
            ],
        ),
    ]
