# Generated by Django 4.2 on 2023-07-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='artista',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='disco',
            name='genero',
            field=models.CharField(default='', max_length=140),
        ),
    ]
